version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: khalid
      MYSQL_DATABASE: investigate
      MYSQL_USER: investigate-admin
      MYSQL_PASSWORD: investigate-pass
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4g
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local

