apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-depl
  labels: 
    app: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nginx
  template: 
    metadata: 
      #labels are assigned to create label that will be matched later 
      labels: 
        app: nginx
    spec:
      containers: 
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 8080