apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-configmap
data: 
  database_url: mongodb-service #reffering it to running mongodb service and the name is same as in mongo.yaml under service meatadata>name