apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mongodb-root-username: dXNlcm5hbWU= #generated password by: echo -n 'username' | base64
  mongodb-root-password: cGFzc3dvcmQ=