apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: public.ecr.aws/docker/library/busybox:unstable-glibc
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: GAME_DEFAULT_ENEMIES
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: game-config-env
              # Specify the key associated with the value
              key: enemies
      # envForm:
      #   - configMapKeyRef: 
      #       name: game-config-env
  restartPolicy: Never
