version: "3.8"

services:
  app:
    container_name: nestjs-caching
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    command: npm run start:dev
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: 
      - redis
    volumes:
      - ./:/app
  redis: 
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data
  
volumes: 
  redis:
    driver: local