import * as _ from 'lodash';
let body = {
  id: 22227,
  networks: {
    metadata: {
      total: 1,
      per_page: 1,
      pages: 1,
      page: 1,
    },
    actions: [],
    results: [
      {
        id: 1,
        name: 'Field Nation',
        type: 'marketplace',
        options: [
          {
            id: 5,
            name: 'Buyer Flat Fee',
            type: 'decimal',
            description: 'Flat fee per job (buyer fee)',
            category: 'payment_fees',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 3,
            name: 'Service Fee Rate',
            type: 'decimal',
            description: 'Percentage of job total (provider fee)',
            category: 'payment_fees',
            visibility: 'all',
            editable: 'staff_admin',
            value: '10',
            default_value: '10',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 2,
            name: 'Buyer Percentage of Service Fee',
            type: 'percent',
            description: 'Buyer share of % fee',
            category: 'payment_fees',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 19,
            name: 'Buyer Service Fee Cap',
            type: 'decimal',
            description: 'Buyer service fee cap',
            category: 'payment_fees',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 20,
            name: 'Provider Service Fee Cap',
            type: 'decimal',
            description: 'Provider service fee cap',
            category: 'payment_fees',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 12,
            name: 'Show Pay to Managed Providers',
            type: 'checkbox',
            description: 'Allow managed providers to see job pay details',
            category: 'settings',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,buyer,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 11,
            name: 'Show Pay to Network Providers',
            type: 'checkbox',
            description: 'Allow independent providers to see job pay details',
            category: 'settings',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 9,
            name: 'Show Pay to Vendors',
            type: 'checkbox',
            description: 'Allow service company admins to see job pay details',
            category: 'settings',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 10,
            name: 'Show Pay to Vendors',
            type: 'checkbox',
            description:
              'Allow service company managed providers to see job pay details',
            category: 'settings',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,buyer,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 8,
            name: 'Field Nation Processes Payments',
            type: 'checkbox',
            description: 'Process provider payments through Field Nation',
            category: 'settings',
            visibility: 'all',
            editable: 'staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 26,
            name: 'Constant Hourly Rate',
            type: 'decimal',
            description: 'Use constant hourly rate',
            category: 'settings',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 4,
            name: 'FN Insurance Program',
            type: 'checkbox',
            description:
              'Apply Field Nation insurance fee if provider does not have insurance',
            category: 'settings',
            visibility: 'all',
            editable: 'staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 1,
            name: 'Pay Network Owner',
            type: 'checkbox',
            description: 'Pay network owner',
            category: 'settings',
            visibility: 'staff,buyer',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 30,
            name: 'Work order pay types',
            type: 'text',
            description: 'Work order pay types',
            category: 'settings',
            visibility: 'all',
            editable: 'staff_admin',
            value: 'blended,fixed,hourly,per_device',
            default_value: 'blended,fixed,hourly,per_device',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 31,
            name: 'Work order minimum hourly pay rate',
            type: 'decimal',
            description: 'Work order minimum hourly pay rate',
            category: 'settings',
            visibility: 'all',
            editable: 'staff_admin',
            value: '',
            default_value: '',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 16,
            name: '(reserved: network) Allow provider signup',
            type: 'checkbox',
            description: 'Allow providers to signup',
            category: 'permissions',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 18,
            name: 'Allow service company signup',
            type: 'checkbox',
            description: 'Allow service companies to signup',
            category: 'permissions',
            visibility: 'staff,buyer,staff_admin',
            editable: 'staff,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 6,
            name: 'Hide Ratings',
            type: 'checkbox',
            description: 'Disable providers from seeing and providing ratings',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 7,
            name: 'Direct Assign',
            type: 'checkbox',
            description: 'Allow direct assignment of providers',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 14,
            name: 'Allow Auto Swap',
            type: 'checkbox',
            description: 'Disable provider swap confirmation',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 15,
            name: 'Disable PQAP',
            type: 'checkbox',
            description:
              'Disable Provider Quality Assurance Program (PQAP) processes',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 13,
            name: 'Join Other Networks',
            type: 'checkbox',
            description: 'Allow providers to join other networks.',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 27,
            name: 'Must be used as the exclusive network on work orders',
            type: 'checkbox',
            description: 'Must be used as the exclusive network on work orders',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 28,
            name: 'Restrict access for newly added users',
            type: 'checkbox',
            description: 'Restrict access for newly added users',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 32,
            name: 'Timesheet Tracking',
            type: 'checkbox',
            description: 'Hours on the work orders are tracked for timesheet',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff_admin',
            value: '0',
            default_value: '0',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 29,
            name: 'Use specific onboarding flow',
            type: 'text',
            description: 'Use specific onboarding flow',
            category: 'permissions',
            visibility: 'all',
            editable: 'staff,staff_admin',
            value: 'none',
            default_value: 'none',
            network_option_role: 'buyer',
            actions: [],
          },
          {
            id: 21,
            name: 'Buy from Network',
            type: 'checkbox',
            description: 'Allow company to buy from network',
            category: 'company_permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 22,
            name: 'Perform Work',
            type: 'checkbox',
            description: 'Allow company to complete work in network',
            category: 'company_permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
          {
            id: 23,
            name: 'Invite Talent',
            type: 'checkbox',
            description: 'Allow company to invite talent to network',
            category: 'company_permissions',
            visibility: 'all',
            editable: 'staff,buyer,staff_admin',
            value: '1',
            default_value: '1',
            network_option_role: 'buyer',
            actions: ['edit'],
          },
        ],
        company_options: [
          {
            company_id: '7404',
            company_name: 'Hegmann Inc',
            buyer_feature: true,
            options: [
              {
                id: 2,
                name: 'Buyer Percentage of Service Fee',
                type: 'percent',
                description: 'Buyer share of % fee',
                category: 'payment_fees',
                visibility: 'all',
                editable: 'staff_admin',
                value: '0',
                default_value: '0',
                network_option_role: 'buyer',
                actions: [],
              },
              {
                id: 3,
                name: 'Service Fee Rate',
                type: 'decimal',
                description: 'Percentage of job total (provider fee)',
                category: 'payment_fees',
                visibility: 'all',
                editable: 'staff_admin',
                value: '0',
                default_value: '10',
                network_option_role: 'buyer',
                actions: [],
              },
              {
                id: 5,
                name: 'Buyer Flat Fee',
                type: 'decimal',
                description: 'Flat fee per job (buyer fee)',
                category: 'payment_fees',
                visibility: 'all',
                editable: 'staff_admin',
                value: '0',
                default_value: '0',
                network_option_role: 'buyer',
                actions: [],
              },
              {
                id: 19,
                name: 'Buyer Service Fee Cap',
                type: 'decimal',
                description: 'Buyer service fee cap',
                category: 'payment_fees',
                visibility: 'all',
                editable: 'staff_admin',
                value: '0',
                default_value: '0',
                network_option_role: 'buyer',
                actions: [],
              },
              {
                id: 20,
                name: 'Provider Service Fee Cap',
                type: 'decimal',
                description: 'Provider service fee cap',
                category: 'payment_fees',
                visibility: 'all',
                editable: 'staff_admin',
                value: '0',
                default_value: '0',
                network_option_role: 'buyer',
                actions: [],
              },
              {
                id: 21,
                name: 'Buy from Network',
                type: 'checkbox',
                description: 'Allow company to buy from network',
                category: 'company_permissions',
                visibility: 'all',
                editable: 'staff,buyer,staff_admin',
                value: '1',
                default_value: '1',
                network_option_role: 'buyer',
                actions: ['edit'],
              },
              {
                id: 22,
                name: 'Perform Work',
                type: 'checkbox',
                description: 'Allow company to complete work in network',
                category: 'company_permissions',
                visibility: 'all',
                editable: 'staff,buyer,staff_admin',
                value: '1',
                default_value: '1',
                network_option_role: 'buyer',
                actions: ['edit'],
              },
              {
                id: 23,
                name: 'Invite Talent',
                type: 'checkbox',
                description: 'Allow company to invite talent to network',
                category: 'company_permissions',
                visibility: 'all',
                editable: 'staff,buyer,staff_admin',
                value: '1',
                default_value: '1',
                network_option_role: 'buyer',
                actions: ['edit'],
              },
            ],
          },
        ],
        sourced_providers: [],
        actions: [],
      },
    ],
  },
  attachments: {
    correlation_id: '951d9b51eb0ed66f7828a58d549ab4a75b3b89a7',
    actions: ['add_slot'],
    sum: {
      unreviewed: 0,
    },
    metadata: {
      total: 2,
      per_page: 2,
      pages: 1,
      page: 1,
    },
    results: [
      {
        id: 1,
        name: 'Documents',
        type: 'document',
        task: {
          id: 0,
          type: {
            id: 0,
          },
        },
        actions: ['upload'],
        metadata: {
          total: 0,
          per_page: 0,
          pages: 1,
          page: 1,
        },
        results: [],
      },
      {
        id: 22519,
        name: 'Misc',
        min_files: 0,
        max_files: 999,
        min_bytes: 1,
        max_bytes: 104857600,
        type: 'slot',
        task: {
          id: 0,
        },
        expense: false,
        actions: ['edit', 'delete', 'upload'],
        metadata: {
          total: 0,
          per_page: 0,
          pages: 1,
          page: 1,
        },
        results: [],
      },
    ],
  },
  shipments: {
    metadata: {
      total: 0,
      per_page: 0,
      pages: 1,
      page: 1,
    },
    results: [],
    correlation_id: '8b3488c6acd8a3be649d65099e7c7764d465f4cf',
    actions: ['add'],
  },
  signatures: {
    metadata: {
      total: 0,
      per_page: 1,
      page: 1,
      pages: 1,
    },
    correlation_id: '076dd31bfaeafb381af7358a2c1249eacce7c7e5',
    actions: [],
    results: [],
  },
  time_logs: {
    actions: [],
    hours: 0,
    metadata: {
      total: 0,
      pages: 1,
      per_page: 0,
      page: 1,
    },
    results: [],
    correlation_id: 'c3c403b8797625fb35cb3aaf59416e6ec5ebeeae',
  },
  problems: {
    metadata: {
      total: 0,
      per_page: 1,
      page: 1,
      pages: 1,
    },
    sum: {
      active: 0,
      resolved: 0,
    },
    correlation_id: '49173dbe2ab6e7d50db941df3ba8535595e94af3',
    actions: ['add'],
    types: [
      {
        id: 72,
        name: 'Internal issue with my company',
        performance_event: false,
        show_pqap_warning: false,
        reportable: true,
        message: '',
        support_ticket: false,
        send_to_buyer: true,
        send_to_provider: false,
        send_to_support: false,
        send_to_accounting: false,
        children: [],
        has_other: false,
      },
      {
        id: 73,
        name: 'How to/Technical assistance',
        performance_event: false,
        show_pqap_warning: false,
        reportable: true,
        message: '',
        support_ticket: true,
        send_to_buyer: true,
        send_to_provider: false,
        send_to_support: true,
        send_to_accounting: false,
        children: [],
        has_other: false,
      },
    ],
    results: [],
  },
  pay: {
    work_order_id: 22227,
    type: 'hourly',
    base: {
      units: 15,
      amount: 60,
    },
    additional: {
      units: 0,
      amount: 0,
    },
    hold: {
      id: 0,
      amount: 0,
      charged: false,
    },
    fees: [
      {
        name: 'cancellation',
        id: 0,
        amount: 0,
        queued: false,
        charged: false,
        hours24_applicable: false,
        calculation: 'fixed',
        at_risk: false,
      },
      {
        name: 'Premier Service Fee',
        display_name: 'Premier Service Fee',
        amount: 45,
        max_amount: 45,
        calculation: 'percent',
        description: 'Buyer pays a 5% service fee per work order.',
        modifier: 0.05,
        breakdown: null,
      },
      {
        name: 'General Liability Liaison',
        display_name: 'General Liability Liaison',
        amount: 0,
        max_amount: 0,
        calculation: 'percent',
        description:
          'Work orders that have General Liability Liaison insurance include an additional 0% fee on the total value of the work order.',
        modifier: 0,
        breakdown: null,
      },
    ],
    finance: {
      id: 0,
      terms: '',
      description: 'Pre-Fund',
      limit: 0,
      invoiced_account: false,
      locked: false,
    },
    hours: 0,
    reported_hours: 0,
    number_of_devices: 0,
    minimum_payment: 20,
    range: {
      min: 60,
      max: 900,
    },
    labor_sum: 60,
    fees_cancellation_pending: false,
    passive_cancellation_amount: 30,
    fee_cancellation_queued: '0',
    fee_cancellation_charged: '0',
    status_id: '1',
    funding: [
      {
        id: 0,
        name: 'Pre-fund',
        amount: 100000,
        custom_name: 'Pre-fund | Available: $100,000.00',
      },
    ],
    invoice: {
      id: 0,
      sent: {
        utc: '',
        local: {
          date: '',
          time: '',
        },
      },
      paid: {
        utc: '',
        local: {
          date: '',
          time: '',
        },
      },
    },
    bonuses: {
      metadata: {
        total: 0,
        per_page: 0,
        page: 1,
        pages: 1,
      },
      sum: {
        all: 0,
        charged: 0,
        uncharged: 0,
      },
      results: [],
      actions: ['add'],
    },
    expenses: {
      metadata: {
        total: 0,
        per_page: 0,
        page: 1,
        pages: 1,
      },
      sum: {
        all: 0,
        charged: 0,
        uncharged: 0,
        pending: 0,
        approved: 0,
        denied: 0,
      },
      results: [],
      actions: ['add', 'deny_all', 'approve_all'],
    },
    penalties: {
      metadata: {
        total: 0,
        per_page: 0,
        page: 1,
        pages: 1,
      },
      sum: {
        all: 0,
        charged: 0,
        uncharged: 0,
      },
      results: [],
      actions: ['add'],
    },
    discounts: {
      metadata: {
        total: 0,
        per_page: 0,
        page: 1,
        pages: 1,
      },
      sum: {
        all: 0,
      },
      results: [],
      actions: [],
    },
    increases: {
      metadata: {
        total: 0,
        per_page: 0,
        page: 1,
        pages: 1,
      },
      minimum: 20,
      sum: {
        all: 0,
      },
      results: [],
      actions: [],
    },
    max_pay: 900,
    total: 60,
    max_pay_limit: 945,
    calculated_total: {
      total: {
        min: 105,
        max: 105,
      },
    },
  },
  publish_stats: {
    requests: 0,
  },
  allow_counter_offers: true,
  is_user_declined: false,
  routes: {
    metadata: {
      total: 0,
      per_page: 0,
      page: 1,
      pages: 1,
    },
    sum: {
      all: 0,
    },
    results: [],
    actions: [],
  },
  custom_fields: {
    actions: [],
    internal: {
      id: 0,
      name: '',
      value: '',
      role: '',
    },
    metadata: {
      total: 1,
      pages: 1,
      per_page: 1,
      page: 1,
    },
    results: [
      {
        id: 1,
        name: 'General',
        order: 1001,
        role: 'buyer',
        metadata: {
          total: 1,
          page: 1,
          pages: 1,
          per_page: 1,
        },
        results: [
          {
            id: 1847,
            name: 'test',
            tip: '',
            type: 'text',
            role: 'buyer',
            dependency: {
              id: 0,
              value: '',
              operator: 'equals',
            },
            options: [],
            flags: [],
            value: '',
            category: 'General',
            order: 1001,
            actions: ['edit'],
          },
        ],
      },
    ],
    correlation_id: '715a9ca817cf2e4e0c9f900b9e757382292564a0',
  },
  qualifications: {
    actions: ['add', 'edit'],
    correlation_id: 'b4fb5de6e2267ba9937caac3d1d8a61d1ef0b160',
    selection_rule: {
      id: 0,
      name: '',
      status: 'match',
      actions: ['delete'],
      total_selection_rule: '0',
      weight: 1,
      sum: {
        total: 1,
        match: 0,
        no_match_optional: 0,
        no_match_required: 1,
      },
      results: [
        {
          id: 64,
          name: 'SC_TYPE_OF_WORK',
          service: '',
          description: 'Provider must have the type of work: Kiosk',
          custom_field: {
            id: 0,
          },
          operation: 'equal_to',
          order: 0,
          extra: '',
          required: true,
          status: 'no_match_required',
          value: 'Kiosk',
          weight: 1,
        },
      ],
      metadata: {
        per_page: 1,
        pages: 0,
        page: 1,
        total: 1,
      },
    },
    ignored_missing_qualifications: false,
  },
  bundle: {
    id: 0,
    company_id: 7404,
    metadata: {
      total: 0,
      per_page: 0,
    },
    results: [],
    actions: [],
  },
  auto_dispatch_stats: {
    auto_assigned: false,
  },
  schedule: {
    work_order_id: 22227,
    service_window: {
      mode: 'exact',
      start: {
        local: {
          date: '2024-08-04',
          time: '14:00:00',
        },
        utc: '2024-08-04 21:00:00',
      },
      end: {
        local: {
          date: '',
          time: '',
        },
        utc: '',
      },
    },
    time_zone: {
      id: 12,
      name: 'America/Phoenix',
      offset: -2,
      short: 'MST',
    },
    status_id: 1,
    company_id: 7404,
    today_tomorrow: 'Tomorrow',
    correlation_id: '1350d78dccf28a129b44996893a4f95fed24de17',
  },
  eta: {
    user: {
      id: 0,
    },
    task: {
      id: 90324,
    },
    start: {
      local: {
        date: '',
        time: '',
      },
      utc: '',
    },
    end: {
      local: {
        date: '',
        time: '',
      },
      utc: '',
    },
    hour_estimate: 0,
    notes: '',
    status: {
      name: 'unconfirmed',
      updated: {
        utc: '',
        local: {
          date: '',
          time: '',
        },
      },
    },
    mode: 'exact',
  },
  location: {
    coordinates: {
      latitude: 33.45,
      longitude: -112.07,
      exact: false,
    },
    work_order_id: 22227,
    mode: 'custom',
    address1: '123 Main Street',
    address2: 'Building 4C',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    country: 'US',
    notes: [],
    type: {
      id: 1,
      name: 'Commercial',
    },
    saved_location: {
      id: 0,
      name: '',
      display_name: '',
      contact: {
        name: '',
        phone: '',
      },
      group: {
        id: 0,
        name: '',
      },
    },
    display_name: 'ABC Corp',
    status_id: 1,
    correlation_id: '60c83dcddc23196069629b0208beeed2b4d76b27',
    zoom: '13z',
    map: {
      url: 'https://api.maptiler.com/maps/streets/static/-112.070000,33.450000,13/320x300@2x.png?key=&attribution=0&markers=-112.07,33.45|,',
      href: 'https://www.google.com/maps/search/123+Main+Street+Phoenix+AZ+85001/@33.45,-112.07,13z',
    },
  },
  company: {
    id: 7404,
    name: 'Hegmann Inc',
    photo: '',
    check_in_instructions: '',
    check_out_instructions: '',
    provider_utilization_max_hours: 0,
    provider_utilization_max_weekly: 0,
    address: {
      address1: '185 Nikita Burg',
      address2: 'Suite 105',
      city: 'Port Lorenachester',
      state: 'MD',
      postalCode: '29420',
      country: 'US',
    },
    features: [
      {
        id: 11,
        name: 'Auto Dispatch',
      },
      {
        id: 12,
        name: 'Training Module',
      },
      {
        id: 19,
        name: 'Task List Management',
      },
      {
        id: 1,
        name: 'Technician Search',
      },
      {
        id: 26,
        name: 'Lipo',
      },
      {
        id: 2,
        name: 'Project Management',
      },
      {
        id: 34,
        name: 'Publish Without Fund',
      },
      {
        id: 39,
        name: 'UI Microservice',
      },
      {
        id: 44,
        name: 'React Work Order Details',
      },
      {
        id: 47,
        name: 'Service Type',
      },
      {
        id: 4,
        name: 'Buy from marketplace',
      },
      {
        id: 7,
        name: 'Penalty Charges',
      },
    ],
  },
  manager: {
    thumbnail:
      'https://s3.amazonaws.com/dev.fieldnation/profile_image/73-5775521499480.png',
    id: 20321,
    username: 'marketplaceBuyer11641821951',
    first_name: 'Cornell',
    last_name: 'Roberts',
    name: 'Cornell Roberts',
    email: 'marketplaceBuyer11641821951@hotmail.com',
    phone: '707-047-3181 x5',
  },
  client: {
    id: 7428,
    name: '730',
  },
  w2: false,
  import_id: 0,
  printable: true,
  status: {
    id: 1,
    name: 'Draft',
    display: 'Draft',
    is_routed: false,
    code: '',
    delay: 0,
    ncns: false,
    sub_status: '',
    confirmed: true,
    correlation_id: 'bcc81196269af4e9776750bb68c1309a24561933',
  },
  messages: {
    metadata: {
      total: 0,
      per_page: 0,
      pages: 1,
      page: 1,
    },
    actions: ['add'],
    results: [],
    correlation_id: '2b08b48c304be61ee2ff6e16cd9caa09eba17757',
  },
  require_registered_service_companies: false,
  assignee: {
    user: {
      id: 0,
      first_name: '',
      last_name: '',
      country: '',
      cell: '',
      phone: '',
      phone_ext: '',
      thumbnail: '/images/missing-profile.png',
    },
    status_id: 1,
    work_order_id: 22227,
    in_confirmation_window: false,
  },
  milestones: {
    created: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    published: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    routed: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    assigned: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    workdone: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    approved: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    paid: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
    canceled: {
      utc: '',
      local: {
        date: '',
        time: '',
      },
    },
  },
  invoice: {
    id: '',
  },
  integrations: null,
  contacts: {
    metadata: {
      total: 2,
      per_page: 2,
      pages: 1,
      page: 1,
    },
    results: [
      {
        id: -2,
        role: 'Work Order Manager',
        name: 'Cornell Roberts',
        email: 'marketplaceBuyer11641821951@hotmail.com',
        phone: '707-047-3181 x5',
        ext: '',
        notes: '',
        actions: ['edit'],
      },
      {
        id: -3,
        role: 'Secondary Contact',
        name: '',
        email: '',
        phone: '',
        ext: '',
        notes: '',
        actions: [],
      },
    ],
    correlation_id: 'c886fa7a301b855d3f874024a907d18e02a6d05f',
    actions: ['edit'],
  },
  tasks: {
    metadata: {
      total: 4,
      per_page: 4,
      pages: 1,
      page: 1,
      completed: {
        confirmassignment: 0,
        checkin: 0,
        checkout: 0,
        closeoutnotes: 0,
      },
    },
    results: [
      {
        id: 90324,
        description: 'Set start time',
        descriptions: {
          task: 'Set start time',
          first: '',
          second: '',
          third: '',
          fourth: '',
        },
        label: 'Set Start Time',
        alerts: [],
        group: {
          label: 'Pre visit',
          id: 'prep',
        },
        type: {
          id: 1,
          key: 'confirmassignment',
          name: 'Set Start Time',
        },
        created: {
          utc: '2024-07-30 06:02:33',
          local: {
            date: '2024-07-29',
            time: '23:02:33',
          },
        },
        author: {
          id: 0,
          first_name: '',
          last_name: '',
        },
        status: 'incomplete',
        eta: {
          user: {
            id: 0,
          },
          task: {
            id: 90324,
          },
          start: {
            local: {
              date: '',
              time: '',
            },
            utc: '',
          },
          end: {
            local: {
              date: '',
              time: '',
            },
            utc: '',
          },
          hour_estimate: 0,
          notes: '',
          status: {
            name: 'unconfirmed',
            updated: {
              utc: '',
              local: {
                date: '',
                time: '',
              },
            },
          },
          mode: 'exact',
          actions: [],
        },
        actions: ['reorder', 'alerts'],
      },
      {
        id: 90326,
        description: 'Check in',
        descriptions: {
          task: 'Check in',
          first: '',
          second: '',
          third: '',
          fourth: '',
        },
        label: 'Check in',
        alerts: [],
        group: {
          label: 'On site',
          id: 'onsite',
        },
        type: {
          id: 3,
          key: 'checkin',
          name: 'Check in',
        },
        created: {
          utc: '2024-07-30 06:02:33',
          local: {
            date: '2024-07-29',
            time: '23:02:33',
          },
        },
        author: {
          id: 0,
          first_name: '',
          last_name: '',
        },
        status: 'incomplete',
        time_log: [],
        actions: ['reorder', 'alerts'],
      },
      {
        id: 90327,
        description: 'Check out',
        descriptions: {
          task: 'Check out',
          first: '',
          second: '',
          third: '',
          fourth: '',
        },
        label: 'Check out',
        alerts: [],
        group: {
          label: 'On site',
          id: 'onsite',
        },
        type: {
          id: 4,
          key: 'checkout',
          name: 'Check out',
        },
        created: {
          utc: '2024-07-30 06:02:33',
          local: {
            date: '2024-07-29',
            time: '23:02:33',
          },
        },
        author: {
          id: 0,
          first_name: '',
          last_name: '',
        },
        status: 'incomplete',
        actions: ['reorder', 'alerts'],
        time_log: [],
      },
      {
        id: 90325,
        description: 'Enter closeout notes',
        descriptions: {
          task: 'Enter closeout notes',
          first: '',
          second: '',
          third: '',
          fourth: '',
        },
        label: 'Enter close out notes',
        alerts: [],
        group: {
          label: 'Post site',
          id: 'post',
        },
        type: {
          id: 2,
          key: 'closeoutnotes',
          name: 'Enter close out notes',
        },
        created: {
          utc: '2024-07-30 06:02:33',
          local: {
            date: '2024-07-29',
            time: '23:02:33',
          },
        },
        author: {
          id: 0,
          first_name: '',
          last_name: '',
        },
        status: 'incomplete',
        actions: ['reorder', 'alerts'],
        closing_notes: '',
        closing_notes_internal: [],
      },
    ],
    correlation_id: 'dd88d2cd9aefcf5ef97d3ceea64b6985e6578acd',
    actions: ['add', 'edit'],
  },
  swaps: {
    metadata: {
      total: 0,
      per_page: 0,
      pages: 1,
      page: 1,
    },
    actions: [],
    results: [],
    correlation_id: 'f711669a636992c22aa0d6caf1cef89d0eba3510',
  },
  equipments: [],
  service_types: [
    {
      id: 71,
      name: 'Installation',
    },
  ],
  site_device: [],
  description: {
    html: 'do this then do that',
    markdown: 'do this then do that',
  },
  confidential: {
    html: '',
  },
  policy_and_procedures: {
    html: '',
    markdown: '',
  },
  standard_instructions: {
    html: '',
    markdown: '',
  },
  progress: {
    sum: {
      all: 4,
      complete: 0,
      incomplete: 4,
    },
    label: 'Tasks',
  },
  advanced_qualifications: true,
  require_gps: false,
  tags: {
    metadata: {
      total: 0,
      per_page: 0,
      pages: 1,
      page: 1,
    },
    actions: ['add'],
    results: [],
    correlation_id: '74d00b5c237aa215fe5ce8a053062ba3fadb263e',
  },
  work_order_id: 22227,
  title: 'Test Automated 1722319350817',
  href: 'https://ui-int.fndev.net/workorders/22227',
  type_of_work: {
    id: 64,
    name: 'Kiosk',
  },
  types_of_work: [],
  closing_notes: '',
  tasks_enabled: true,
};
let model = {
  id: 'number',
  networks: 'object',
  sites: 0,
  attachments: 'object',
  shipments: 'object',
  signatures: 'object',
  time_logs: 'object',
  problems: 'object',
  pay: {
    work_order_id: 'number',
    type: 'string',
    base: 'object',
    additional: 'object',
    hold: 'object',
    fees: 'object',
    payment: 0,
    finance: 'object',
    client_payment_enabled: 0,
    client_payment_terms: 0,
    hours: 'number',
    can_view: 0,
    buyer_approval_time_days: 0,
    client_payment_terms_copy: 0,
    client_payment_terms_updated_copy: 0,
    target_review_period: 0,
    reported_hours: 'number',
    number_of_devices: 'number',
    minimum_payment: 'number',
    range: 'object',
    actions: 0,
    labor_sum: 'number',
    fees_cancellation_pending: 'boolean',
    passive_cancellation_amount: 'number',
    fee_cancellation_queued: 'string',
    fee_cancellation_charged: 'string',
    status_id: 'string',
    funding: 'object',
    invoice: 'object',
    correlation_id: 0,
    bonuses: 'object',
    expenses: 'object',
    penalties: 'object',
    discounts: 'object',
    increases: 'object',
    pricing_insights: 0,
    positive: 0,
    currency_style: 0,
    max_pay: 'number',
    total: 'number',
    max_pay_limit: 'number',
    fn_process_payment: 0,
    total_by_role: 0,
    total_before_fees_by_role: 0,
    calculated_total: 'object',
    is_taxable_location: 0,
  },
  pay_old: 0,
  pay_service: {
    workOrderId: 0,
    userId: 0,
    lineItems: 0,
    fees: 0,
    totals: 0,
    ledger: 0,
    attributes: 0,
    from_cache: 0,
  },
  publish_stats: {
    has_preferred_requests: 0,
    has_preferred_counters: 0,
    requests: 'number',
    counter_offers: 0,
    routes: 0,
    declines: 0,
    all_requests: 0,
    correlation_id: 0,
  },
  requests: 0,
  allow_counter_offers: 'boolean',
  is_user_declined: 'boolean',
  routes: 'object',
  custom_fields: 'object',
  qualifications: 'object',
  ratings: {
    correlation_id: 0,
    buyer: 0,
    assigned_provider: 0,
  },
  bundle: 'object',
  auto_dispatch_stats: 'object',
  schedule: {
    work_order_id: 'number',
    service_window: 'object',
    time_zone: 'object',
    status_id: 'number',
    company_id: 'number',
    today_tomorrow: 'string',
    correlation_id: 'string',
    actions: 0,
  },
  conflicts: 0,
  eta: {
    user: 'object',
    task: 'object',
    start: 'object',
    end: 'object',
    hour_estimate: 'number',
    notes: 'string',
    status: 'object',
    mode: 'string',
    actions: 0,
  },
  location: {
    coordinates: 'object',
    work_order_id: 'number',
    mode: 'string',
    address1: 'string',
    address2: 'string',
    city: 'string',
    state: 'string',
    zip: 'string',
    country: 'string',
    notes: 'object',
    type: 'object',
    saved_location: 'object',
    display_name: 'string',
    status_id: 'number',
    correlation_id: 'string',
    zoom: 'string',
    map: 'object',
    actions: 0,
  },
  holds: 0,
  company: {
    id: 'number',
    name: 'string',
    photo: 'string',
    check_in_instructions: 'string',
    check_out_instructions: 'string',
    provider_utilization_max_hours: 'number',
    provider_utilization_max_weekly: 'number',
    address: 'object',
    features: 'object',
  },
  manager: {
    thumbnail: 'string',
    id: 'number',
    username: 'string',
    first_name: 'string',
    last_name: 'string',
    name: 'string',
    email: 'string',
    phone: 'string',
  },
  client: { id: 'number', name: 'string' },
  project: { id: 1, name: 1 },
  w2: 'boolean',
  import_id: 'number',
  printable: 'boolean',
  status: {
    id: 'number',
    name: 'string',
    display: 'string',
    is_routed: 'boolean',
    code: 'string',
    delay: 'number',
    ncns: 'boolean',
    sub_status: 'string',
    confirmed: 'boolean',
    correlation_id: 'string',
  },
  messages: 'object',
  require_registered_service_companies: 'boolean',
  assignee: {
    user: {
      id: 'number',
      first_name: 'string',
      last_name: 'string',
      email: 1,
      country: 'string',
      cell: 'string',
      phone: 'string',
      phone_ext: 'string',
      thumbnail: 'string',
    },
    status_id: 'number',
    work_order_id: 'number',
    in_confirmation_window: 'boolean',
    actions: 0,
  },
  milestones: {
    time_to_dispatch: 0,
    time_to_work_done: 0,
    time_alive: 0,
    time_to_approve: 0,
    created: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    published: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    routed: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    assigned: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    workdone: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    approved: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    paid: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
    canceled: {
      utc: 'string',
      local: {
        date: 'string',
        time: 'string',
      },
    },
  },
  service_contract: { id: 0, name: 0 },
  template: { id: 1, name: 1 },
  invoice: 'object',
  team: { id: 0, name: 0 },
  integration: 1,
  integrations: 'object',
  contacts: 'object',
  tasks: 'object',
  swaps: 'object',
  equipments: 'object',
  service_types: 'object',
  site_device: 'object',
  high_potential: 0,
  special_skill: {
    id: 0,
    required: 0,
    certification_id: 0,
    dynamic_term_id: 0,
    name: 0,
    feeReduction: 0,
    fee: 0,
    international: 0,
  },
  description: {
    html: 'string',
    markdown: 'string',
    actions: 0,
  },
  confidential: 'object',
  policy_and_procedures: {
    html: 'string',
    markdown: 'string',
  },
  standard_instructions: {
    html: 'string',
    markdown: 'string',
  },
  progress: {
    sum: {
      all: 'number',
      complete: 'number',
      incomplete: 'number',
    },
    label: 'string',
  },
  advanced_qualifications: 'boolean',
  pending_routing_provider: 0,
  attributes: {
    fn_one_overage: 0,
    marketplace_overage: 0,
    general_liability_liaison: 0,
    applied_constant_hourly_rate: 0,
    survey_id: 0,
  },
  require_gps: 'boolean',
  utc_convert_off: 1,
  role: 0,
  workflow_completion: 0,
  tags: 'object',
  work_order_id: 'number',
  actions: 0,
  title: 'string',
  correlation_id: 0,
  href: 'string',
  type_of_work: { id: 'number', name: 'string' },
  closing_notes: 'string',
  tasks_enabled: 'boolean',
  workflow_publish_or_route: 0,
  workflow_cancel: 0,
  timings: 0,
  auto_dispatch: 1,
  types_of_work: [],
};
function dataCheck(objValue, srcValue, key) {
  if (objValue == undefined) {
    console.log({ objValue, srcValue, key});
  }
}
const bodyFiltered = _.mergeWith(body, model, dataCheck);
export { model, body, bodyFiltered };
